import fs from 'fs'
import path from 'path'

const PREAMBLE_START = '<!-- ANPM_PREAMBLE_START - DO NOT EDIT -->'
const PREAMBLE_END = '<!-- ANPM_PREAMBLE_END -->'
// Legacy markers for backwards compatibility with already-installed agents
const LEGACY_PREAMBLE_START = '<!-- RELAY_PREAMBLE_START - DO NOT EDIT -->'
const LEGACY_PREAMBLE_END = '<!-- RELAY_PREAMBLE_END -->'

/**
 * bin/anpm-preamble.sh 스크립트를 생성한다.
 * bash 실행 가능 환경을 전제로, anpm CLI를 직접 호출한다.
 */
export function generatePreambleScript(slug: string, _apiUrl: string): string {
  return `#!/usr/bin/env bash
# anpm-preamble.sh — auto-generated by anpm publish
set +e

# Usage ping (background, non-blocking)
if command -v anpm &>/dev/null; then
  anpm ping "${slug}" --quiet 2>/dev/null &
fi

# Update check (already 24h cached by relay CLI)
if command -v anpm &>/dev/null; then
  _UPD=$(anpm check-update "${slug}" --quiet 2>/dev/null || true)
  [ -n "$_UPD" ] && echo "$_UPD" || true
fi

echo "ANPM_READY: ${slug}"
`
}

/**
 * SKILL.md / command에 삽입할 preamble 마크다운.
 * agentDir: 설치된 에이전트의 절대 경로 (install 시점에 결정)
 */
export function generatePreamble(slug: string, agentDir: string): string {
  const scriptPath = path.join(agentDir, 'bin', 'anpm-preamble.sh')
  return `${PREAMBLE_START}
## Preamble (run first)

\`\`\`bash
[ -f "${scriptPath}" ] && bash "${scriptPath}" 2>/dev/null || true
\`\`\`

If output shows \`CLI_UPGRADE_AVAILABLE <old> <new>\`: tell user "anpm v{new} available. Run: npm update -g anpm"
If output shows \`AGENT_UPGRADE_AVAILABLE\`: ask (use AskUserQuestion tool) user "${slug} v{new} is available (by @{author}). Update now? (anpm update ${slug})". If user agrees, run \`anpm update ${slug}\` before proceeding.
${PREAMBLE_END}`
}

/**
 * agentDir에 bin/anpm-preamble.sh를 생성한다.
 */
export function generatePreambleBin(agentDir: string, slug: string, apiUrl: string): void {
  const binDir = path.join(agentDir, 'bin')
  if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, { recursive: true })
  }
  const scriptPath = path.join(binDir, 'anpm-preamble.sh')
  fs.writeFileSync(scriptPath, generatePreambleScript(slug, apiUrl))
  fs.chmodSync(scriptPath, 0o755)
}

/**
 * frontmatter(---...---) 뒤에 preamble을 삽입한다.
 */

export function injectPreamble(filePath: string, slug: string, agentDir: string): void {
  const content = fs.readFileSync(filePath, 'utf-8')
  const preamble = generatePreamble(slug, agentDir)

  // 기존 preamble 제거 (새 마커 + 레거시 마커 모두 처리)
  let cleaned = content
  for (const [start, end] of [[PREAMBLE_START, PREAMBLE_END], [LEGACY_PREAMBLE_START, LEGACY_PREAMBLE_END]]) {
    const startIdx = cleaned.indexOf(start)
    const endIdx = cleaned.indexOf(end)
    if (startIdx !== -1 && endIdx !== -1) {
      cleaned =
        cleaned.slice(0, startIdx).trimEnd() +
        '\n' +
        cleaned.slice(endIdx + end.length).trimStart()
    }
  }

  // frontmatter 뒤에 삽입
  const fmMatch = cleaned.match(/^---\n[\s\S]*?\n---\n/)
  if (fmMatch) {
    const fmEnd = fmMatch[0].length
    cleaned =
      cleaned.slice(0, fmEnd) +
      '\n' + preamble + '\n\n' +
      cleaned.slice(fmEnd).trimStart()
  } else {
    cleaned = preamble + '\n\n' + cleaned.trimStart()
  }

  fs.writeFileSync(filePath, cleaned)
}

/**
 * 에이전트의 사용자 진입점 파일에 preamble을 주입한다.
 */
export function injectPreambleToAgent(agentDir: string, slug: string): number {
  let count = 0

  // 1. user-invocable 서브 스킬 SKILL.md
  const skillsDir = path.join(agentDir, 'skills')
  if (fs.existsSync(skillsDir)) {
    function walkSkills(dir: string) {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          walkSkills(fullPath)
        } else if (entry.name === 'SKILL.md') {
          const content = fs.readFileSync(fullPath, 'utf-8')
          if (/user-invocable:\s*true/i.test(content)) {
            injectPreamble(fullPath, slug, agentDir)
            count++
          }
        }
      }
    }
    walkSkills(skillsDir)
  }

  // 2. commands/*.md
  const commandsDir = path.join(agentDir, 'commands')
  if (fs.existsSync(commandsDir)) {
    for (const entry of fs.readdirSync(commandsDir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue
      injectPreamble(path.join(commandsDir, entry.name), slug, agentDir)
      count++
    }
  }

  return count
}
