import fs from 'fs'
import path from 'path'

const PREAMBLE_START = '<!-- RELAY_PREAMBLE_START - DO NOT EDIT -->'
const PREAMBLE_END = '<!-- RELAY_PREAMBLE_END -->'

/**
 * bin/relay-preamble.sh 스크립트를 생성한다.
 * relay CLI가 있으면 사용, 없으면 curl fallback.
 */
export function generatePreambleScript(slug: string, apiUrl: string): string {
  // slug format: @owner/team → extract team slug for ping
  const stripped = slug.startsWith('@') ? slug.slice(1) : slug
  const slashIdx = stripped.indexOf('/')
  const teamSlug = slashIdx !== -1 ? stripped.slice(slashIdx + 1) : stripped
  return `#!/usr/bin/env bash
# relay-preamble.sh — auto-generated by relay publish
set +e

DEVICE_HASH=$(echo "$HOSTNAME:$USER" | shasum -a 256 | cut -d' ' -f1)

# Usage ping
if command -v relay &>/dev/null; then
  relay ping "${slug}" --quiet 2>/dev/null &
else
  curl -sf -X POST "${apiUrl}/api/teams/${teamSlug}/ping" \\
    -H "Content-Type: application/json" \\
    -d "{\\"device_hash\\":\\"$DEVICE_HASH\\"}" \\
    2>/dev/null &
fi

# Update check
if command -v relay &>/dev/null; then
  _UPD=$(relay check-update "${slug}" --quiet 2>/dev/null || true)
  [ -n "$_UPD" ] && echo "$_UPD" || true
fi

echo "RELAY_READY: ${slug}"
`
}

/**
 * SKILL.md / command에 삽입할 preamble 마크다운.
 * 단순히 relay ping을 호출한다.
 */
export function generatePreamble(slug: string): string {
  const teamPath = slug.startsWith('@') ? slug.slice(1) : slug
  return `${PREAMBLE_START}
## Preamble (run first)

\`\`\`bash
bash "$HOME/.relay/teams/${teamPath}/bin/relay-preamble.sh" 2>/dev/null || true
\`\`\`

If output shows \`CLI_UPGRADE_AVAILABLE <old> <new>\`: tell user "relay v{new} available. Run: npm update -g relayax-cli"
If output shows \`TEAM_UPGRADE_AVAILABLE\`: tell user "${slug} v{new} available (by @{author}). Run: relay update ${slug}"
${PREAMBLE_END}`
}

/**
 * teamDir에 bin/relay-preamble.sh를 생성한다.
 */
export function generatePreambleBin(teamDir: string, slug: string, apiUrl: string): void {
  const binDir = path.join(teamDir, 'bin')
  if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, { recursive: true })
  }
  const scriptPath = path.join(binDir, 'relay-preamble.sh')
  fs.writeFileSync(scriptPath, generatePreambleScript(slug, apiUrl))
  fs.chmodSync(scriptPath, 0o755)
}

/**
 * frontmatter(---...---) 뒤에 preamble을 삽입한다.
 */
export function injectPreamble(filePath: string, slug: string): void {
  const content = fs.readFileSync(filePath, 'utf-8')
  const preamble = generatePreamble(slug)

  // 기존 preamble 제거
  let cleaned = content
  const startIdx = cleaned.indexOf(PREAMBLE_START)
  const endIdx = cleaned.indexOf(PREAMBLE_END)
  if (startIdx !== -1 && endIdx !== -1) {
    cleaned =
      cleaned.slice(0, startIdx).trimEnd() +
      '\n' +
      cleaned.slice(endIdx + PREAMBLE_END.length).trimStart()
  }

  // frontmatter 뒤에 삽입
  const fmMatch = cleaned.match(/^---\n[\s\S]*?\n---\n/)
  if (fmMatch) {
    const fmEnd = fmMatch[0].length
    cleaned =
      cleaned.slice(0, fmEnd) +
      '\n' + preamble + '\n\n' +
      cleaned.slice(fmEnd).trimStart()
  } else {
    cleaned = preamble + '\n\n' + cleaned.trimStart()
  }

  fs.writeFileSync(filePath, cleaned)
}

/**
 * 팀의 사용자 진입점 파일에 preamble을 주입한다.
 */
export function injectPreambleToTeam(teamDir: string, slug: string): number {
  let count = 0

  // 1. user-invocable 서브 스킬 SKILL.md
  const skillsDir = path.join(teamDir, 'skills')
  if (fs.existsSync(skillsDir)) {
    function walkSkills(dir: string) {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          walkSkills(fullPath)
        } else if (entry.name === 'SKILL.md') {
          const content = fs.readFileSync(fullPath, 'utf-8')
          if (/user-invocable:\s*true/i.test(content)) {
            injectPreamble(fullPath, slug)
            count++
          }
        }
      }
    }
    walkSkills(skillsDir)
  }

  // 2. commands/*.md
  const commandsDir = path.join(teamDir, 'commands')
  if (fs.existsSync(commandsDir)) {
    for (const entry of fs.readdirSync(commandsDir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue
      injectPreamble(path.join(commandsDir, entry.name), slug)
      count++
    }
  }

  return count
}
